services:
  - type: web
    name: sv-saude-virtual-api
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
    disk:
      name: sqlite-data
      mountPath: /var/www/html/database
      sizeGB: 1
